---
title: "Logbooks Table Generator"
output: github_document
encoding: UTF-8
---

This notebook generates a table of logbook gaps that are included in our analyses. The table is generated from the `skipped_logbook_periods.csv` file and the `updated_skipped_logbook_periods.csv` file. The table is saved as `logbook_gaps.html` in the `output` folder.

## Load required packages

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# name required packages
list.of.packages <- c("ggplot2", "glue", "gt", "tidyverse", "webshot", "paletteer", "gtExtras", "here")

# install required packages, if necessary, and load them ----
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[, "Package"])]
if (length(new.packages) > 0) {
    install.packages(new.packages, repos = "https://cloud.r-project.org/")
}

# Instead of using require, we'll use library to load the packages
lapply(list.of.packages, library, character.only = TRUE)

```

##  Load Data and Generate Tables

```{r}
read_csv_safe <- function(file_path) {
    if (file.exists(file_path)) {
        return(readr::read_csv(file_path, ))
    } else {
        stop(glue::glue("File {file_path} does not exist."))
    }
}

# Use here to build the paths to your CSV files
skipped_periods_path <- here::here("data", "skipped_logbook_periods.csv")
updated_skipped_periods_path <- here::here("data", "updated_skipped_logbook_periods.csv")

# Now you can use these paths in your read_csv_safe function
skipped_periods <- read_csv_safe(skipped_periods_path)
updated_skipped_periods <- read_csv_safe(updated_skipped_periods_path)

# Convert all character columns to UTF-8
skipped_periods[] <- lapply(skipped_periods, function(x) {
    if (is.character(x)) {
        return(iconv(x, to = "UTF-8"))
    }
    x
})
# Convert all character columns to UTF-8
updated_skipped_periods[] <- lapply(updated_skipped_periods, function(x) {
    if (is.character(x)) {
        return(iconv(x, to = "UTF-8"))
    }
    x
})
```


### Logbook Gaps

```{r}
gap_table <- skipped_periods %>%
    gt() %>%
    tab_spanner(label = "The 7 large gaps in the logbooks", columns = c(logbook_dates, logbook_interval)) %>%
    tab_spanner(label = "The 8 small gaps in the logbooks", columns = c(skipped_dates, skipped_interval)) %>%
    cols_width(c(skipped_dates, logbook_dates) ~ px(300)) %>%
    cols_label(
        logbook_dates = md("Dates of Identified Gap"),
        logbook_interval = "Duration of Gap",
        skipped_dates = md("Dates of Identified Gap"),
        skipped_interval = "Duration of Gap"
    ) %>%
    cols_align(align = "left", columns = c(skipped_dates, logbook_dates)) %>%
    cols_align(align = "center", columns = c(skipped_interval, logbook_interval)) %>%
    tab_header(
        title = md("Identified Logbook Gaps"),
        subtitle = md("Larger gaps on the left are included in our analyses, while smaller ones on the right are skipped.")
    ) %>%
    opt_table_font(font = list("Times New Roman", "Cochin", "Serif"), weight = "normal")

gap_table
```

### Updated Logbook Gaps

```{r}
updated_gap_table <- updated_skipped_periods %>%
  gt() %>%
  cols_width(
    c(dates) ~ px(300),
  )  %>%
  cols_label(
    dates = md("Dates of Identified Gap"),
    interval = "Duration of Gap",
  ) %>%
  cols_hide(
    columns = c(
      status, start, end
    )
  ) %>% cols_align(
    align = "left", columns = c(dates)
  )  %>% cols_align(
    align = "center", columns = c(interval)
  ) %>% tab_header(
    title = md('All Identified Logbook Gaps'),
    subtitle = md('Longer included gaps are in bold, while shorter ones are skipped.')
  ) %>% opt_table_font(
    font = list( "Times New Roman",
      "Cochin", "Serif"
    ),
    weight= 'normal'
  ) %>% tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = cells_body(
      columns = c(interval, status),
      rows = (status == 'included')
    )
  )
updated_gap_table
```


